from extensions import db

class Manager(db.Model):
    __tablename__ = 'manager_form'
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.Date)
    date1 = db.Column(db.Date)

    emp_name = db.Column(db.String(255))
    department = db.Column(db.String(255))
    period_of_review = db.Column(db.String(255))
    reviewer = db.Column(db.String(255))
    reviewers_title = db.Column(db.String(255))
    job_Knowledge = db.Column(db.String(255))
    productivity = db.Column(db.String(255))
    work_quality = db.Column(db.String(255))
    technical_skills = db.Column(db.String(255))
    work_consistency = db.Column(db.String(255))
    enthusiasm = db.Column(db.String(255))
    cooperation = db.Column(db.String(255))
    attitude = db.Column(db.String(255))
    initiative = db.Column(db.String(255))
    work_relations = db.Column(db.String(255))
    creativity = db.Column(db.String(255))
    punctuality = db.Column(db.String(255))
    attendance = db.Column(db.String(255))
    dependability = db.Column(db.String(255))
    communication_skills = db.Column(db.String(255))
    overall_rating = db.Column(db.String(255))
    opportunities = db.Column(db.String(255))
    reviewers_comments = db.Column(db.String(255))
    job_Knowledge_comments = db.Column(db.String(255))
    productivity_comments = db.Column(db.String(255))
    work_quality_comments = db.Column(db.String(255))
    technical_skills_comments = db.Column(db.String(255))
    work_consistency_comments = db.Column(db.String(255))
    enthusiasm_comments = db.Column(db.String(255))
    cooperation_comments = db.Column(db.String(255))
    attitude_comments = db.Column(db.String(255))
    initiative_comments = db.Column(db.String(255))
    work_relations_comments = db.Column(db.String(255))
    creativity_comments = db.Column(db.String(255))
    punctuality_comments = db.Column(db.String(255))
    attendance_comments = db.Column(db.String(255))
    dependability_comments = db.Column(db.String(255))
    communication_skills_comments = db.Column(db.String(255))
    overall_rating_comments = db.Column(db.String(255))
    signaturepath = db.Column(db.String(255))

    date = db.Column(db.Date)
    IP_addr = db.Column(db.String(255))
    Location = db.Column(db.String(255))
    UserAgent = db.Column(db.String(255))
    OperatingSystem = db.Column(db.String(255))
    Time = db.Column(db.DateTime)